version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestExternalCheckProject
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/TestExternalCheckProject
  gitUsername: PoojaAnandGit
  gitBranch: main
